FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /config
ADD ./requirements.txt /config/
RUN pip install -r /config/requirements.txt
RUN mkdir /src;
EXPOSE 8000
WORKDIR /src
COPY . /src/
# Run the app.  CMD is required to run on Heroku
# $PORT is set by Heroku
CMD celery --app=stajedemodanas worker --loglevel=info