FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /config
ADD ./requirements.txt /config/
RUN pip install -r /config/requirements.txt
RUN mkdir /src;
EXPOSE 8000
WORKDIR /src
COPY . /src/
# Run the app.  CMD is required to run on Heroku
# $PORT is set by Heroku
CMD python manage.py makemigrations && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn stajedemodanas.wsgi -b 0.0.0.0:8000 --timeout 300