version: '2'
services:
  stajedemodanas_nginx:
    image: nginx:latest
    container_name: stajedemodanas_nginx01
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - ./static:/src/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - stajedemodanas_web
    networks:
      - stajedemodanas_default
      - default
  stajedemodanas_web:
    build: .
    container_name: stajedemodanas_web01
    restart: on-failure
    env_file:
      - ./.env
      - ./.env.secret
    command: bash -c "python manage.py makemigrations && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn stajedemodanas.wsgi -b 0.0.0.0:8000 --timeout 300"
    depends_on:
      - stajedemodanas_db
    volumes:
      - .:/src
      - ./static:/src/static
    expose:
      - "8000"
    networks:
      - stajedemodanas_default
      - default
  stajedemodanas_db:
    image: "postgres:10.3-alpine"
    restart: always
    env_file:
    - ./.env.secret
    ports:
    - "5432:5432"
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
  stajedemodanas_celery-flower:
    build: .
    command: celery -A stajedemodanas flower --port=5556
    ports:
      - "5556:5556"
    volumes:
      - .:/src
    depends_on:
      - stajedemodanas_db
  stajedemodanas_rabbit:
    image: rabbitmq:latest
    container_name: stajedemodanas_rabbit

networks:
  stajedemodanas_default:
     external: false