# Generated by Django 2.1 on 2018-11-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliverers', '0001_initial'),
        ('receivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverers.Address')),
            ],
            options={
                'verbose_name': 'Receiver Company',
                'verbose_name_plural': 'Receiver Companies',
            },
        ),
        migrations.CreateModel(
            name='ReceiverGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
            ],
            options={
                'verbose_name': 'Receiver Group',
                'verbose_name_plural': 'Receiver Groups',
            },
        ),
        migrations.RenameField(
            model_name='receiver',
            old_name='collector_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='receiver',
            old_name='collector_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='receiver',
            old_name='collector_nickname',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='receiver',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivergroup',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receivers.Receiver'),
        ),
        migrations.AddField(
            model_name='receivergroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receivers.ReceiverCompany'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receivers.ReceiverCompany'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receivers.ReceiverGroup'),
        ),
    ]
