# Generated by Django 2.1 on 2018-11-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivers', '0002_auto_20181122_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
