# Generated by Django 2.1 on 2018-12-03 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receivers', '0003_receiver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
