"""
Django settings for stajedemodanas project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import configparser
import os
import django_heroku

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

config = configparser.ConfigParser()
config.read('stajedemodanas.ini')

MONGO_SERVER = config['MONGODB']['mongoServer']
MONGO_DATABASE_NAME = config['MONGODB']['mongoDatabaseName']
MONGO_DATABASE_PORT = config['MONGODB']['mongoDatabasePort']
RABBIT_SERVER = config['RABBIT']['rabbitServer']
RABBIT_PORT = config['RABBIT']['rabbitPort']
RABBIT_USER = config['RABBIT']['rabbitUser']
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wbr&!ak@l+hk*))c4ivxl7hy=u7h3o+((#luvq0+p%=h5#mv#u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my stuff
    'bootstrap4',
    'django_countries',
    'crispy_forms',
    'django_celery_results',
    'django_celery_beat',

    # my apps
    'stajedemodanas',
    'deliverers',
    'receivers',
    'workplaces',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stajedemodanas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stajedemodanas.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': f'{MONGO_DATABASE_NAME}',
        'HOST': f'{MONGO_SERVER}',
        'PORT': int(MONGO_DATABASE_PORT),
    }
}


# Mogodb on Heroku
# DATABASES = {
#   'default': {
#     'ENGINE': 'django_mongodb_engine',
#     'NAME': 'heroku_app1234567',
#     'USER': 'heroku_app1234567',
#     'PASSWORD': 'abcdefghijklmnopqrstuvwxyz',
#     'HOST': 'ds031117.mongolab.com',
#     'PORT': '31117',
#   }
# }

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_FAIL_SILENTLY = not DEBUG

CELERY_RESULT_BACKEND = 'django-db'
BROKER_CONNECTION_TIMEOUT = 10


# END --------------------------
django_heroku.settings(locals())
