# Generated by Django 2.1 on 2018-08-19 09:41

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address line 2')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(blank=True, max_length=1024, null=True, verbose_name='City')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverer_name', models.CharField(max_length=100)),
                ('deliverer_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120, verbose_name='Item Name')),
                ('item_description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Item Description')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Item Price')),
                ('item_deliverer_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Code')),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliverers.Deliverer')),
            ],
            options={
                'verbose_name': 'Delivery Item',
                'verbose_name_plural': 'Delivery Items',
            },
        ),
    ]
