# Generated by Django 2.1 on 2018-11-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverer',
            options={'verbose_name': 'Deliverer', 'verbose_name_plural': 'Deliverers'},
        ),
        migrations.RenameField(
            model_name='deliverer',
            old_name='deliverer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deliverer',
            old_name='deliverer_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='deliveryitem',
            old_name='item_deliverer_code',
            new_name='deliverer_code',
        ),
        migrations.RenameField(
            model_name='deliveryitem',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='deliveryitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deliveryitem',
            old_name='item_price',
            new_name='price',
        ),
    ]
